### PR TITLE
Fix issue #202

### LINKED ISSUE #202: Not implemented scalafx.concurrent.ScheduledService for javafx.concurrent.ScheduledService

### PR DESCRIPTION
**Pull request by dbronecki**
Implement wrapper for javafx.concurrent.ScheduledService.
This fixes #202 

I hope this wrapper is well written, other classes like Service was inspiration for me while writing this one. If there is something I need to improve, please let me know!

### CODE REVIEW

**Comment by dbronecki** [comment]
I see that two Travis CI builds failed, but this is because of wrong java version used in build - you can see in logs that 1.8.0_31 version was used (too old). On my computer project build fine.

**Comment by jpsacha** [comment]
Travis sometimes runs with a wrong version of JDK. Restarting the build tends to gets the right JDK. I restarted Travis test manually looks that jet the right JDK this time.
I will try to take a look at the PR later today.

**Comment by jpsacha** [comment]
Can you add wrappers for the static fields like `EXPONENTIAL_BACKOFF_STRATEGY`.

**Comment by dbronecki** [comment]
Static fields wrappers added

**Comment by jpsacha** [comment]
Thanks for implementing the wrapper.

**Pull request merged**
