### PR TITLE
Updated constants to camel case instead of caps and underscores.

### PR DESCRIPTION
**Pull request by MarkCLewis**
I attempted to find all the constants in the project that used the Java style naming and I updated them to the Scala style. I also made changes to the demos that used that code so that everything is happy on compile.

### CODE REVIEW

**Comment by hohonuuli** [comment]
While that is the "official" naming convention according to Martin Odersky himself. Not every group out there follows it. For example, in [Databrick's style guide](https://github.com/databricks/scala-style-guide#naming)* they recommend following the Java convention of CAPITAL_UNDERSCORE names. 

Also, I've found for projects that mix Java and Scala code, for example, pretty much every JavaFX/ScalaFX project I've done, the Scala naming convention is confusing.

* Databricks is the company behind [Spark](https://spark.apache.org/)

**Comment by MarkCLewis** [comment]
The problem is that ScalaFX is currently inconsistent. It appears that everything was originally added using the Java style, then many things, but not all, were switched to the Scala style. While it is unlikely that there would be general agreement on which style is superior, I think it is safe to say that the library should be internally consistent.

My motivation for doing this right now is that I have a textbook that will be published in 2016 that uses ScalaFX for the GUIs and graphics. It would be nice if whatever style I use in the code for the book were actually still able to compile in 2-3 years.

**Comment by MichaelJAllen** [comment]
Firstly, this problem is described by Issue #75. Please post updates to any changes made there, and include that issue in any relevant commits/pull requests if possible. Ideally, for backwards compatibility, the old *Java*-style constants should be retained, but marked as **deprecated**. (Otherwise, you risk breaking every existing *ScalaFX* application.)

All in all, we've had a number of discussions about this issue. The outcome is that, since *ScalaFX* is supposed to be a *Scala* flavor of *JavaFX*, that it should therefore follow *Scala* conventions whenever possible. Consequently, constants should have *Scala* camel-case names, with the first letter being a capital. In a similar vein, *ScalaFX* has *Scala*-style *getter* and *setter* functions to replace those in *JavaFX*. That's about as "official" a line for *ScalaFX* as you're likely to encounter.

However, from my personal viewpoint, there's an awful lot of drudgery involved in implementing this in a *Scala* layer, with some risk of error (constant values becoming inconsistent with the right values in *JavaFX*) yet with almost no added-value. However, this is currently mandated by the nature of *ScalaFX* classes delegating their functionality to the corresponding *JavaFX* class. One big problem we have is that many of the new *Java* 8 builds introduce new *JavaFX* API changes which aren't reflected in the *ScalaFX* API unless updates are made. This then ties *ScalaFX* to a specific *Java* 8 build. But that's a whole other issue...

In my own projects, I've moved away from *ScalaFX* to a degree. I use those parts of it that add value, such as the binding operators, but otherwise I mostly just use *JavaFX* as is. Where I can add value in a *Scala* API, I've chosen to use implicit classes, that allow *Scala* decorations to be added to a *JavaFX* class. That works a lot better when inheriting from *JavaFX* classes, is less susceptible to problems with changes to the *JavaFX* API, and also means that I don't have to provide one-for-one mappings for every constant, function, etc. in *JavaFX* to its *Scala* equivalent. It's also more efficient in both CPU loading and memory usage. Just saying...

**Comment by MarkCLewis** [comment]
This pull request has all of the old Java versions still present and marked as deprecated following the conversions used previously in ScalaFX.

As for use of ScalaFX, it turns out that JavaFX can't be used in a scripting mode, and I using the scripting mode for my introductory course. I could switch to straight JavaFX in the second course, but the code required to make things work is uglier than I would like to include in that course.

**Comment by MichaelJAllen** [comment]
Mark, the only issue I'd have with your pull request is that it only addresses the *ScalaFX* 8 release. Ideally, changes that affect the *ScalaFX* 2 API (on the **SFX-2** branch) should be made on that branch, then merged from there into the master branch. That way, both releases are covered. That said, it's not the end of the world if the **SFX-2** branch doesn't get the updates.

BTW, could you elaborate on what you mean by "*JavaFX* can't be used in a scripting mode"? Could you give an example?

**Comment by jpsacha** [comment]
@hohonuuli
[The Scala Guide Naming Convention](http://docs.scala-lang.org/style/naming-conventions.html) recommends using upper camel case convention for constants. As Mike mentioned, original problem was that there was (and still is) a mixture of conventions used. Issue #75 called for cleaning it up. Upper camel case seems like more Scala-like choice.

@MichaelJAllen
Java 7 is no longer officially supported for public releases by Oracle. It is difficult to maintain two separate branches for Java 7 and Java 8. Currently, effectively the `SFX-2` branch (for Java 7) is dormant. Main contributions should should be assumed to support JavaFX 8 and committed to the `master` branch. This was briefly [discussed](https://groups.google.com/forum/#!topic/scalafx-dev/O0AqDSdgP7U) on `scalafx-dev`. I will correct the main README and update the branching policy stated there that still calls for `SFX-2`.

**Comment by hohonuuli** [comment]
@jpsacha Yes, you are correct about the Scala naming convention recommending upper camel case. I'm pointing out that it's __not__ universally followed even by high-visibility projects such as [Apache Spark](https://spark.apache.org/). I think that adopting it in ScalaFX is a bad practice as it is confusing for folks coming from JavaFX and adds one more thing to keep in mind when translating JavaFX example code to ScalaFX. Deprecating the Java style name while also adding the Scala name also adds more clutter to wade through in the API. That's just my 2 cents.

**Comment by jpsacha** [comment]
Agreed that there is more than one naming convention in use.  Each has its pros and cons.
In issue #75, we agreed earlier to settle on one of them for ScalaFX, with its positives and negatives. This PR adds to previous PRs and brings issue #75 very close to resolution.

**Comment by MarkCLewis** [comment]
@MichaelJAllen, I have not yet found a way to write a JavaFX program that I can run as a script with Scala. Consider the following ScalaFX script.

```scala
import scalafx.application.JFXApp
import scalafx.scene.Scene
import scalafx.scene.control._

val app = new JFXApp {
  stage = new JFXApp.PrimaryStage {
    scene = new Scene {
      val message = new Label("Hello?")
      content = message
    }
  }
}

app.main(args)
```

I can run this by just executing `scala ScalaFXScript.scala`. Using JavaFX, I can get the same behavior from an application with this code.

```scala
import javafx.application.Application
import javafx.stage.Stage
import javafx.scene.Scene
import javafx.scene.control._

class JavaFX extends Application {
  def start(stage:Stage):Unit = {
    val message = new Label("Hello?")
    stage.setScene(new Scene(message))
    stage.show;
  }
}

object JavaFX {
  def main(args:Array[String]):Unit = {
    Application.launch(classOf[JavaFX], args:_*)
  }
}
```

However, I can't run that as a script. It have to compile it and run it as an application. Even if I could get it to run as a script, lines like the one in the `main` method are really unfriendly for notice programmers, but the ScalaFX script is very straightforward.

**Comment by MichaelJAllen** [comment]
@MarkCLewis, thanks for the example.

One of the nice, value-added things *ScalaFX*'s `JFXApp` trait does is to use *Scala*'s `DelayedInit` trait (which is, ironically, deprecated in *Scala* as of release 2.11) to delay execution of the application's constructor—the initialization of `app` in your Scala code—until everything else has been initialized, and in particular, *JavaFX*. Furthermore, it then executes that constructor code on the *JavaFX* thread, so that everything works just fine. (*JavaFX*, as you're no doubt aware, runs on a separate thread, and only accepts commands issued on that thread.) It's simple, clear and easy to understand.

When you switch to the *JavaFX* equivalent, the initial problem is that your `main` function will never execute, so you need to invoke it manually (as you also had to do at the end of the *ScalaFX* version), using:

```scala
JavaFX.main(args)
```

at the end of your script. At this point, things fall over because *JavaFX* must use reflection to find the default constructor for your `JavaFX` class, and this doesn't appear to work for a class defined in a script. (The `Application.launch` method throws a `NoSuchMethodException` while looking for `Main$$anon$$JavaFX.<init>()`, which is just the `JavaFX` class's constructor.) Strangely, if I execute your code in the *Scala REPL* manually, then it works just fine. Maybe it's a bug?

I'm sure there must be a solution to this, but I haven't found it yet.

**Comment by jpsacha** [comment]
@MarkCLewis, @MichaelJAllen
Could you move the discussion of running ScalaFX from script from this unrelated PR to, say, [scalafx-user](https://groups.google.com/forum/#!forum/scalafx-users)? This is an interesting topic that others may be to able participate in or learn from.

Thanks

**Comment by MarkCLewis** [comment]
I just attempted to put a discussion there with my comments. I didn't feel comfortable directly quoting @MichaelJAllen, so I will leave it to him to respond with his text from this thread if he wishes.

**Pull request merged**
